name: Zhao Lab Website
description: Lab Website of Dr. Haiqing Zhao's Research Group at UTMB
url: https://zhaolabutmb.github.io/

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins: ['jekyll-twitter-plugin']

redcarpet: 
  extensions:
   - tables
   
exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - vendor/
  - vendor/**/*

projects:
  - ex
